apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sops-secrets
    namespace: admin
spec:
    # https://github.com/isindir/sops-secrets-operator/blob/147febf336f14bb2546eec020680ce1b2a2e96f1/api/v1alpha3/sopssecret_types.go#L33
    secretTemplates:
        - name: ENC[AES256_GCM,data:nKVW1E3R1kQ=,iv:xCDOlXCUnQk8+voaVnrsyGcU1UYex7Yd8CViH26uRPE=,tag:O17M183KGJz0PGorzTLfnw==,type:str]
          stringData:
            configuration.secret.yml: ENC[AES256_GCM,data:yAmZoLww1xzBBKpkLzH6V5w8Zz7rUzvHLtRtLbixys0NqBzUDP4DJACTkNDatuFPDeZ96vd22VZXY5aPab19Xn4pTzSy8uCojcUJPydQwWq67QAWaLaMxCs4hJYtfc+vVBTzN3kPJt8djtQx8O7foH6+9hTDfJc7c1DnT86KdI1OiKdp7gqcSegadlVgoNbhLWOeFy1fVz8Z5Dk5wEKclggtcw3I/y0Sk5XTTxtuNveQysw5PsOiI/DQQK8Z7Pe/SF86V99xd//kGkM7XIqUoixdA33WgFK720reJ8lrIUIGnXw5gV4v5mO3o0crGsMxFyfj/e25ONH27+m3sGdX/i3pPSa2kVDmfPX9lJYTB2Ek8JEaXe7y1jK/2TO2qkjSjVoUSEj+CBuo0+p/v1ptzCYdd4SiKbYz63eUtX+X7OPSSTpHGbNrFow2K4HXn/uCRuHGoAZvqFstVvlp0m3l8sDwh3v6CswbBvYkz199hbfCKeSLcrjjPWI3l6lnVDMooBL3As/5DTU8W4xr8jfFEcwIk8gkJQjEmkmXx/xyjThgfbHPsxbzkK34aXmG2rzgPufScZJWzKTJY4zzoF6PMudnAQj9Umax4ukXBmLdsTD7QfSi8LIxIOdMYGphXPxnRWCnXDsoE3mPRTTQKfNB7oRrKMUf9xF48JTCoRgrLFEmjJb5AU3JbmmVTX0C4q7bUodsPU8EUyOwWirviyZAq9w5523DXof7rCVd+H0CeDaz7bOzHtLSBBxwWXESJF9vIXBtaq6m4Nj9jFskm1cWF+eKUSZHA858unNjNjiO4ZDneX57C+r8ePLxW6ATGpt3rxMfMT0JYrYjPtELyCoAqauDTypPMIarvrg2fl9jV6AayKo+MClzuS0dUM1xrsU2PIZEIqZTZmEehgJl4danhmhupJSV+U0IMJ8uR8cazZj0Jb7NlOVIrZAxdWeRUBf0HezYkvbumWrm/tnPrs8/jZK+K0b8EGkhVDt28S3D674jPKXa3cwO93+dXutYcge4gtN45NHWUsO/8OQv1SQQiOzAGDqH2cg1WP3Wdafj5YKlDQvi5LGGhzDEXbo2I/+BoYOJIhBZrYC7h3HCbf/bytIqVfmuomWzLpxCfOKxDshShPI5G/PtK5W4KJpaO9xBDUbKX8qm9Gdh3sDM/s42q6CLvkUUIubg3lpIRR5Y53YB2PamfdLDVU4O0X6mCsJgHPYFgykdzt6nN4h1Q77cpldtZV0td5uT/5R9FGzd3bexLVtFT5AkUh4mjUShkuVSPiD0fgyTT5u37ZB2UjSOYO2DJgAS7h4//Zfm/azkSa29iZ3ChwyEnXAq563S+mqOi10vREFEGi1vvnPTM71Uj2FVrvp5+1shNnAD1POfeMM/TgGYoo5XwW/jV9Vz7UPkJicvpeAUT6ZQ7TuQkTCRFRCh0qt9kXreI/7o8qnTx0NO6KP61v35VVCaeHEG7b7DToV8eL8v2npuIkI2p1Fxo7EBBKyODuARjoh9DHbA99Dgq097OnMGatUifZMCDSFZFbuGqt+Qbn/oJKd8rX8GfT4NiiKQHbIUWe3+JqgeSmpuUoeiJqIbSiGHn8MJtF3J66b44dCT3fZEl3UK9h8TRGhX63TM3zxN3awpwL9LJid3EQ1rdnEJjY5+15e6ShhMhP5beaseqzwGCG1DxGIwaRm81YBRSlUSQV/vh5wQ/eJ5Vsib3B8C4n4DagjnfY+K0PEkkTSvekkz9NJw2iA+0Lt5lSU0gfCZ5csTiYhrZtf6xQo9Y1MxbFRaRifb6k9AwwYTr8x0FQ/kBzLfg5Ee+U7GFosQYYj8PjF1SBxKS600D1HbUYFxP8Vpz/d/ejyaGuRefZzEbaT+urhA56CapaPGZK/4irhXnAcCj5m2SuCsLyqm4S6wH5pSffqCCfsreoQqkZqbz2OAUT45SKah1nYixg/h3wpra8ILAq+4uHpnH1qNlb58YCP24TR3lODWkoG5qNGTSuITbRXkF0AWmuMOihLX+hoGlf0wsYhPIiVz+V1pufLkB9eRxIeYhOxplR292sIeI8AT8Djx6rloq/aoXSaAQz3s+P2efZNTZIuiUdc75EdaUpbpeaCl8ZmsUHSY3+W/VGzeA2fGCE6sOcKKVx7RMkAfq0TmTe7heV336jcwgwm9NYMFKoQmbACAiX5R8QsIdsKhTGDDx2i6Ye3WUkyrdJur6X7C8a1gS2vMW/0LnmwxugB9NoaIsYDblUKwxKT84fUN9Sc91X9ACK/7kdZgq6IhYt2f1nHRdGI3BLfYo/ElQaJkHvBqBYUwn+f/79kzgsfREMaR4Zy83EEH4wILEESz2acVzvgZCG0E3tW9ny3T26e4tuhMOnViIsy+znqngj5RfA6H+ChpDzP91jmcDqRQ0ipSF2X6kA/ujufDwF7CiPor1PG81K6RMb+e70N67tFYQpMLFbIjzDrb0CF3AQ98HuKWcnunkUhF4vZq+IYoD7nhqpndpgSSCPK72Kiy0weMfjJtzT5XW/nfFb8qsFP4aR3xhC+VfiDJfw8c9TyMLLPFe8v9ZSgrKdJJm2h6L0OfJIsLBtsYKBHTnmIVx5Xd5UC4jxTCUjgGiWHZlSlSa9vRNkuqLSmpN+YlQjkhcikjDK50Wjux/m2JV7Z6if/aHxwaoimSn49o3RG3FkU0Q42TkS15Oq/3MLkjO9n3JHHW4cb3VjrZ3QfF/Tu/w4IqmQIKpHcXV6zKPFWvnHkdrQW895+MJBCLD0G0lpwgwQS3Cn7bzWiNvDeUhUjehk9RFXX19aEh1YRyzNDXXdzotNxuvNWBaAUtKhlibS3o9cYtQbMhavv4hmzhdZONPu0I1mzvzgjMEAzLvezDi0uX8klVKrleqrB795REZuEzvVlQbAXfQ+5W3rXZkod5Bhm2jZQVb7PsCIjXHrsY+QF/PLSmrKjdXRtzA8/gjyc0cc6qdqLn4rLd56zfNhc2vXPGMUYyVMMlEUWe6XijsT9SQAjxPjSyKTKTNBSz2+fai+GdUzdlUBItQMCEcfaEl3+gaevP+zxTakLglhcWj8hx3w8t5zosDbveJAiv6gQpLcNC4AQxO+5UQsjiFHtskRadiCrInyiv7qOJ0HzcbCZWoe3IKpjlU8BZ7o6BzGJuOh1mT3h+gi8uysud98QxuVBQb1bwi5rUfvwMimXk4dI+T3kWSAMt7napgv5bBWw60TWWv3sA3yB/lhZ/,iv:qTLJqCO9BSoVnjVXu9s7oAMRxjzgjfxIzOuf9yZrLdA=,tag:I3tRF5006Y/zOfDi6iXj5A==,type:str]
        - name: ENC[AES256_GCM,data:AwzNqAywh6UgtvLzmao=,iv:521LhNJ2PM1Gy4lKZygXhglo7FdcnqlTUffv4fDkOSM=,tag:1R2kiDJiHFDwNMAg9PdeBg==,type:str]
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:+R0Ra8kI2yI5FcnXMfPa00KxnfE=,iv:UjWw6q+goGD9SlP5njEe2sybLGzAG6BGz4Yug7B3BjA=,tag:uvie+IA4kLxVDEIniQMPoQ==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:XSsfP9DfPqJtKKwpUF1DwzGNqj3j/srFfEIDV280MP1TIwyR4uKgvw==,iv:GMulgmJHb+jyWlC36ijyG1kefzGuLuw0Kow1c+V4wIQ=,tag:F1R5NUurNzCFEyEZwuG3PQ==,type:str]
            RESTIC_REPOSITORY: ENC[AES256_GCM,data:ozGssvXpjcvpknkQ5TWg8PUJeQk62B7fsip/r1NH+EYIDQGAR2sBn7paAzlIPCY=,iv:85xSAINv3ig2ORVXdVleSvuTZ2Wv7TVLUS/tmzuuEto=,tag:XiV3q0kcE73obiKHZ7bJvw==,type:str]
            RESTIC_PASSWORD: ENC[AES256_GCM,data:Cpj1ZDTz8a8xYdjRVdfpYT9eR4BKlQBu207AN9DxrvoQDSui0EkkJFdvz6Y=,iv:NPlLyaFlxR2m8rhoxBfPqUTXJlXSfU6LsOEqu1tNzjo=,tag:U+/YNhAqT+JrKYI5KZ8JDg==,type:str]
sops:
    age:
        - recipient: age1se1qd0xew8nru2cmy7u9mvy9wr8lxj2zs6k0fysthpdj8kjuuryn6vwv6fsh04
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZ5Ry9wUSBBMEZRVEZX
            aXlYQU45aW5admI5YkpiMWRIMGxzektGbXNWaGxoa3VxOGxRTwpvVmNGYTRobURB
            cm5EeGl0NEJzNHJQcHRFblp2VHp4aWdxSllhWk1nTkRzCi0tLSAxRkRtTDBQa1E5
            TnVRa3dkTHhHNWxaSUtMWEZ3SktUaDVWbWZTWDA0QjE4Cpg3CVP53vpwIUC3DKft
            C7OK6R3QxlBIDEoxAe+nTDiuaXFf4agOJLRO91wGYYDbLfYInX4J2nUSg3Y+3R3a
            oZQ=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye7q4uvexwhruvm5p9svw9z5tu58v9uk6r9pv4aue8j7v0lmpqus5ug9az
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUGtRMC9oaExVTHVzdEJO
            cFBjV1BuajlzNFRIengxNGtTQWFDNUJqWUNjCnlUWG9JT2FsTnRZMHVyYjlpQXY2
            dmtFemcza3NaK1VVZ3kvanhCVkdCTkEKLS0tICtEeDdQUUMxUzFTbTlzZkhRaEww
            ejhGd0V5ZzU0clVVc084Mm1QN1RPSmMKXMN8IpwaHXj2TC5gBoh5dKsn1JW4kfc/
            60S856zHsdx+l8lw7OudAywLm97z7M0dWP1SrFZunaDMnONw/mFsCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-02T08:35:50Z"
    mac: ENC[AES256_GCM,data:vphkSDt3+sN5Nev+BGqlBD5ABewY49Cbv4xSQnchWfrjVhXpCzcJJXJlj0T/ubjaY1N1NyIAQGvd2ajC3swPaapA37KKcSbBMkub8S5LxeHOI+CWFq272s23ys49nh0mhOAuh6f2uFS8EB4ndk7s4TljaRCC2U/HF+QTQrND2N0=,iv:iX0h/6Gkt5HSMCjWvwCnYa33bSYjLLbTXZ5YhLLwKtw=,tag:6uVAoyxXTmsgHQovkv13nA==,type:str]
    encrypted_suffix: Templates
    version: 3.10.2
---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sops-secrets
spec:
    # https://github.com/isindir/sops-secrets-operator/blob/147febf336f14bb2546eec020680ce1b2a2e96f1/api/v1alpha3/sopssecret_types.go#L33
    secretTemplates:
        - name: ENC[AES256_GCM,data:a+fPUmxfYg==,iv:G15dV3Fn3TBP7la3pX6tBbi7KnzEI+9riFuudUwjTeQ=,tag:2Gs+Lp4TiSZhIqtuXLBUCw==,type:str]
          stringData:
            secret_key: ENC[AES256_GCM,data:p8Al0QaszjFQOaMtrF/hegrSd8MZd+YnR6yS5H2DvwdPZZNTVu9fvJuWHKU=,iv:BCdi6YcLgTC58fdlhnU6aEbclHSf2Y6Yjn5oGwqvkf8=,tag:MRb8AXfZzJYV3s65Gh4Bqg==,type:str]
            mailer_passwd: ENC[AES256_GCM,data:N5MmTPRLiR2rcVng9QBs17O6wAMOxkdNdh0CL1jzECtRUmqltDud7MA/GtinD8D4iPM=,iv:SRzUeicnAhj63wnSjrivDSwbVqSM0yyE4LzbRqatskg=,tag:/rzjE2h3ZM3NeKiyJ46Dag==,type:str]
        - name: ENC[AES256_GCM,data:pXVLP0tAIAFyscVIS8lWMcv8,iv:H7eQ9ijQRjmDoRpRXM65A47XlA7GF3gz7u0xk+ZoXu8=,tag:nIaGzSuvts2VMCQxHY1I9A==,type:str]
          stringData:
            ANTHROPIC_API_KEY: ENC[AES256_GCM,data:FtHkdo4vYYWaAlPyypwqo+EbO0YMwQAK75LAWzW0gvx/ypNkXRMFlMmrLZnTrkVP6wuF2gd3DFBfp2pFJVuzho4QWZ1SR8PjtCh7/8SiSvHlaso5H9+8rRExtqeLY8ifu6V56/p1mM5XjlRm,iv:FPIonoWcWVPAjIwmUcrnYZrg0KALxQfwr5Y3CG+x8RA=,tag:zQslyXi3CTehU/cDDXNY1Q==,type:str]
            GOOGLE_PSE_API_KEY: ENC[AES256_GCM,data:0rFYiPTB3tx4hp/+GnfaGm2Hw4hdkFAj6aJOgeCWTLHHzRx9QAzP,iv:UwA3qq40v7msBkINKsLGkmi8Zlv8dFa9N37j+s94IEc=,tag:+oLtWCpI2Y63jG28MByw0w==,type:str]
            GOOGLE_PSE_ENGINE_ID: ENC[AES256_GCM,data:9KA/QiFsInKb1AOpPGGzvjw=,iv:tWbcz2tiQtb4Zd4bQjT2cvWwCGGxGWfmCLdYbuvBPbM=,tag:/dRuhQUduWLCWhT5kTXy+g==,type:str]
            OPENAI_API_KEY: ENC[AES256_GCM,data:9CgpEB+sRfziihaVAcO3yny5H2+48HT9Sjk8q0N3YULYyV4Mk/z8UCbQfziNry0AocCQ,iv:i++G4/sdNbqAPG4JwCehi3aAOp47pSTQ+6zm1FHVOKo=,tag:v9JDv5yIW1VAcKPF9gMMow==,type:str]
            SERPLY_API_KEY: ENC[AES256_GCM,data:lQH+xpOdBBHTs10fD04whAu/F6pz/25s,iv:zTOXcc9Q5vH+a+A7FL14sFCbJ1rlHxF0oneE5u+qRjQ=,tag:/1Rk/awOFfTGQvL9V9PnCA==,type:str]
            WEBUI_SECRET_KEY: ENC[AES256_GCM,data:v4fJeBB4M1I/RWqKT+44HwoNVlOsHTElytecpsOrT800PWcHvsaHD3TAqV4=,iv:BjP3xVBTP8YTjBa0SSStrNDDtPGc8IC3uGRNyFu0xgs=,tag:0ZVDm4q0zbRp4tzSQbHY8Q==,type:str]
        - name: ENC[AES256_GCM,data:Iziy36xBOxouVtfjFkOi0Wo6KA==,iv:uukWLZpAdFxmXdcJf6Nmm5FGtyceMPLttLG/p6YP2oo=,tag:GXYxzv7riwbgL3v7FFTS+g==,type:str]
          stringData:
            production.json: ENC[AES256_GCM,data:dGd33/Zllfoieh8df5redDM3Ij/Ab+R5zFccc16UQbxZ6WD2MBS9p4iZbG0vZ84Q1xO8tWsVZmlA5eb4GUoHc1ga0ne/H1ZxuIkJnvEu5l+qVvoLQBG/m3SXh/wQG1Obp2KWFZ01h6q0kGFZcY5uQp1F2ZJ0cKzmt3ioH4yO4EbCCqEqkjRNlkDnAZoTW8Q4xuB0+BtpG6jq1bsX0KWJ9NOvtAitqXzG+zvWnMpx81DqzLKLb/uHufEEMZZ9Kk/E7N/fr4lHWKx5PtaRJb7ff6s5IsRMSOZ3yCgu1IP1nuRm+g==,iv:sOnB+Yvpqgp8AsIo0fGUyxnKkTtWOLDjF5Pxp6c1PwM=,tag:eIhOc0ljo8TbvrfKVEX0Zg==,type:str]
        - name: ENC[AES256_GCM,data:uwlsdKDsaGrPTOXIdI7n/KHyLDGS,iv:WDkqSHO6XzxRsJW/ZBvc3OwcXridw2I/JSZpoVdD8h0=,tag:RFY2b9Z1aQqUbmwiw/8HvQ==,type:str]
          type: ENC[AES256_GCM,data:smzgGA/19CtQvLF5VGdNfsgrjJ2r9qYJjMI/ypLx,iv:qf6M0wMw5H/kyehanJBZigOzk1g++C6a27ezxLKS6Q0=,tag:px2t8RL81i3K58jYbdZDQw==,type:str]
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:NxnojJQoXT4ncfiGyx0IP6r6eU8qakgNWFmpsxq98YRraBqT8kpfGWs9MuqYxE2ZMkulDsaJgR3Or9/KBE6d5uG9i7yQDeiaPQPFgJyoymQVE7yH1AMIzqGBpC06/4GjM1yYY1uq+HoLZYjKAZKEFzekeZiqBsGDz/lqBAg=,iv:KftjTzGLptn46iBccW1yd/iBSJwkX/u9tqMzEAxUMzI=,tag:6rO/ADluroaQbnbgehHliQ==,type:str]
sops:
    age:
        - recipient: age1se1qd0xew8nru2cmy7u9mvy9wr8lxj2zs6k0fysthpdj8kjuuryn6vwv6fsh04
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZ5Ry9wUSBBMEZRVEZX
            aXlYQU45aW5admI5YkpiMWRIMGxzektGbXNWaGxoa3VxOGxRTwpvVmNGYTRobURB
            cm5EeGl0NEJzNHJQcHRFblp2VHp4aWdxSllhWk1nTkRzCi0tLSAxRkRtTDBQa1E5
            TnVRa3dkTHhHNWxaSUtMWEZ3SktUaDVWbWZTWDA0QjE4Cpg3CVP53vpwIUC3DKft
            C7OK6R3QxlBIDEoxAe+nTDiuaXFf4agOJLRO91wGYYDbLfYInX4J2nUSg3Y+3R3a
            oZQ=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye7q4uvexwhruvm5p9svw9z5tu58v9uk6r9pv4aue8j7v0lmpqus5ug9az
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUGtRMC9oaExVTHVzdEJO
            cFBjV1BuajlzNFRIengxNGtTQWFDNUJqWUNjCnlUWG9JT2FsTnRZMHVyYjlpQXY2
            dmtFemcza3NaK1VVZ3kvanhCVkdCTkEKLS0tICtEeDdQUUMxUzFTbTlzZkhRaEww
            ejhGd0V5ZzU0clVVc084Mm1QN1RPSmMKXMN8IpwaHXj2TC5gBoh5dKsn1JW4kfc/
            60S856zHsdx+l8lw7OudAywLm97z7M0dWP1SrFZunaDMnONw/mFsCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-02T08:35:50Z"
    mac: ENC[AES256_GCM,data:vphkSDt3+sN5Nev+BGqlBD5ABewY49Cbv4xSQnchWfrjVhXpCzcJJXJlj0T/ubjaY1N1NyIAQGvd2ajC3swPaapA37KKcSbBMkub8S5LxeHOI+CWFq272s23ys49nh0mhOAuh6f2uFS8EB4ndk7s4TljaRCC2U/HF+QTQrND2N0=,iv:iX0h/6Gkt5HSMCjWvwCnYa33bSYjLLbTXZ5YhLLwKtw=,tag:6uVAoyxXTmsgHQovkv13nA==,type:str]
    encrypted_suffix: Templates
    version: 3.10.2
---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sops-secrets
    namespace: cert-manager
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:+vztK5fiprvA4eD+hds=,iv:BXIqN/p/tlXDn0GnJagIZDtHjdGpEyJRd/pWTlQu3r4=,tag:FwvYa8tDVhTu0r+u/FBJMQ==,type:str]
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:PGSoeHHu+BqHnWhv3moI/F5gfko=,iv:N/gPw7erqLcKpRQCpDST60cWkMBXSsE5tP5pQnwNbDw=,tag:UyEUCh8LPo043CXtVc2XkQ==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:5qFhusPdd9VqdkdkNf2bAujcVIr+Zb2AM5HhVthTg9OajeBB3yiG9w==,iv:FWKR4Cw5Fc+GSh9VrXpymzsGyfPv6ZxozygveCUdgmU=,tag:FDNWOCllWWyEmjJ99rWuVg==,type:str]
sops:
    age:
        - recipient: age1se1qd0xew8nru2cmy7u9mvy9wr8lxj2zs6k0fysthpdj8kjuuryn6vwv6fsh04
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZ5Ry9wUSBBMEZRVEZX
            aXlYQU45aW5admI5YkpiMWRIMGxzektGbXNWaGxoa3VxOGxRTwpvVmNGYTRobURB
            cm5EeGl0NEJzNHJQcHRFblp2VHp4aWdxSllhWk1nTkRzCi0tLSAxRkRtTDBQa1E5
            TnVRa3dkTHhHNWxaSUtMWEZ3SktUaDVWbWZTWDA0QjE4Cpg3CVP53vpwIUC3DKft
            C7OK6R3QxlBIDEoxAe+nTDiuaXFf4agOJLRO91wGYYDbLfYInX4J2nUSg3Y+3R3a
            oZQ=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye7q4uvexwhruvm5p9svw9z5tu58v9uk6r9pv4aue8j7v0lmpqus5ug9az
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUGtRMC9oaExVTHVzdEJO
            cFBjV1BuajlzNFRIengxNGtTQWFDNUJqWUNjCnlUWG9JT2FsTnRZMHVyYjlpQXY2
            dmtFemcza3NaK1VVZ3kvanhCVkdCTkEKLS0tICtEeDdQUUMxUzFTbTlzZkhRaEww
            ejhGd0V5ZzU0clVVc084Mm1QN1RPSmMKXMN8IpwaHXj2TC5gBoh5dKsn1JW4kfc/
            60S856zHsdx+l8lw7OudAywLm97z7M0dWP1SrFZunaDMnONw/mFsCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-02T08:35:50Z"
    mac: ENC[AES256_GCM,data:vphkSDt3+sN5Nev+BGqlBD5ABewY49Cbv4xSQnchWfrjVhXpCzcJJXJlj0T/ubjaY1N1NyIAQGvd2ajC3swPaapA37KKcSbBMkub8S5LxeHOI+CWFq272s23ys49nh0mhOAuh6f2uFS8EB4ndk7s4TljaRCC2U/HF+QTQrND2N0=,iv:iX0h/6Gkt5HSMCjWvwCnYa33bSYjLLbTXZ5YhLLwKtw=,tag:6uVAoyxXTmsgHQovkv13nA==,type:str]
    encrypted_suffix: Templates
    version: 3.10.2
