apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sops-secrets
    namespace: admin
spec:
    # https://github.com/isindir/sops-secrets-operator/blob/147febf336f14bb2546eec020680ce1b2a2e96f1/api/v1alpha3/sopssecret_types.go#L33
    secretTemplates:
        - name: ENC[AES256_GCM,data:nKVW1E3R1kQ=,iv:xCDOlXCUnQk8+voaVnrsyGcU1UYex7Yd8CViH26uRPE=,tag:O17M183KGJz0PGorzTLfnw==,type:str]
          stringData:
            AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:zFeLENL5foTNSzrRGAS4zPJPmgmzLjEK/7gFxxDsKUAePCZqfS7AVKhv8yA=,iv:DrHnz4Qut70spY8RMkenkopLYfch963yeVXBmL3iaMU=,tag:dvLcx8YshLiU6lbDOOZoAw==,type:str]
            AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ENC[AES256_GCM,data:7fgSiDjDn5dqRVsw+xjNVOioYyiCPeCjbBywxYCNZpb3acBUQNOuRpCePk8=,iv:ZEEMUbZAytD6z62DJk30jZKJz124b+SOxoknzs9ygxU=,tag:fTKWM4zePwdF5oWhURbf6Q==,type:str]
            AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:mm05t/v8jwxXKuUhlt7YwLe81W3hWC9ONRXm8tYp/EkpG+wq4SINP+iGjuc=,iv:nRaLcp5OrsigZ5jJMS/swe0L5z4dApDJ0t6ktB6ALUA=,tag:VWcxf0RTDWrLkHKkqaTzlg==,type:str]
sops:
    age:
        - recipient: age1se1qd0xew8nru2cmy7u9mvy9wr8lxj2zs6k0fysthpdj8kjuuryn6vwv6fsh04
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZ5Ry9wUSBBMEZRVEZX
            aXlYQU45aW5admI5YkpiMWRIMGxzektGbXNWaGxoa3VxOGxRTwpvVmNGYTRobURB
            cm5EeGl0NEJzNHJQcHRFblp2VHp4aWdxSllhWk1nTkRzCi0tLSAxRkRtTDBQa1E5
            TnVRa3dkTHhHNWxaSUtMWEZ3SktUaDVWbWZTWDA0QjE4Cpg3CVP53vpwIUC3DKft
            C7OK6R3QxlBIDEoxAe+nTDiuaXFf4agOJLRO91wGYYDbLfYInX4J2nUSg3Y+3R3a
            oZQ=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye7q4uvexwhruvm5p9svw9z5tu58v9uk6r9pv4aue8j7v0lmpqus5ug9az
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUGtRMC9oaExVTHVzdEJO
            cFBjV1BuajlzNFRIengxNGtTQWFDNUJqWUNjCnlUWG9JT2FsTnRZMHVyYjlpQXY2
            dmtFemcza3NaK1VVZ3kvanhCVkdCTkEKLS0tICtEeDdQUUMxUzFTbTlzZkhRaEww
            ejhGd0V5ZzU0clVVc084Mm1QN1RPSmMKXMN8IpwaHXj2TC5gBoh5dKsn1JW4kfc/
            60S856zHsdx+l8lw7OudAywLm97z7M0dWP1SrFZunaDMnONw/mFsCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-05T11:25:17Z"
    mac: ENC[AES256_GCM,data:h1t6k6CfYTfp3wpg5+9cWEeyUf7mLL/0TgbEQlXQsaRen+c3RhOgptPBMeB3AGhVbwCDhYhWZ5NiARzMwa8iK0gFryDWa1qsK2BUGD3fwZQTlxhW1A+X8JxjVA1KbjhNwrXywH5gn3ld0Qg/Qoi7eiiIgx+tidcs3zRVZTtPfHQ=,iv:S8zIBHpoEIvkjOV8p/X4Tfn39qfFn+kwtYEWYu5Wy+Y=,tag:325tt9X2jVqjPaSkJWZyUA==,type:str]
    encrypted_suffix: Templates
    version: 3.10.2
---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sops-secrets
spec:
    # https://github.com/isindir/sops-secrets-operator/blob/147febf336f14bb2546eec020680ce1b2a2e96f1/api/v1alpha3/sopssecret_types.go#L33
    secretTemplates:
        - name: ENC[AES256_GCM,data:pXVLP0tAIAFyscVIS8lWMcv8,iv:H7eQ9ijQRjmDoRpRXM65A47XlA7GF3gz7u0xk+ZoXu8=,tag:nIaGzSuvts2VMCQxHY1I9A==,type:str]
          stringData:
            ANTHROPIC_API_KEY: ENC[AES256_GCM,data:FtHkdo4vYYWaAlPyypwqo+EbO0YMwQAK75LAWzW0gvx/ypNkXRMFlMmrLZnTrkVP6wuF2gd3DFBfp2pFJVuzho4QWZ1SR8PjtCh7/8SiSvHlaso5H9+8rRExtqeLY8ifu6V56/p1mM5XjlRm,iv:FPIonoWcWVPAjIwmUcrnYZrg0KALxQfwr5Y3CG+x8RA=,tag:zQslyXi3CTehU/cDDXNY1Q==,type:str]
            GOOGLE_PSE_API_KEY: ENC[AES256_GCM,data:0rFYiPTB3tx4hp/+GnfaGm2Hw4hdkFAj6aJOgeCWTLHHzRx9QAzP,iv:UwA3qq40v7msBkINKsLGkmi8Zlv8dFa9N37j+s94IEc=,tag:+oLtWCpI2Y63jG28MByw0w==,type:str]
            GOOGLE_PSE_ENGINE_ID: ENC[AES256_GCM,data:9KA/QiFsInKb1AOpPGGzvjw=,iv:tWbcz2tiQtb4Zd4bQjT2cvWwCGGxGWfmCLdYbuvBPbM=,tag:/dRuhQUduWLCWhT5kTXy+g==,type:str]
            OPENAI_API_KEY: ENC[AES256_GCM,data:9CgpEB+sRfziihaVAcO3yny5H2+48HT9Sjk8q0N3YULYyV4Mk/z8UCbQfziNry0AocCQ,iv:i++G4/sdNbqAPG4JwCehi3aAOp47pSTQ+6zm1FHVOKo=,tag:v9JDv5yIW1VAcKPF9gMMow==,type:str]
            SERPLY_API_KEY: ENC[AES256_GCM,data:lQH+xpOdBBHTs10fD04whAu/F6pz/25s,iv:zTOXcc9Q5vH+a+A7FL14sFCbJ1rlHxF0oneE5u+qRjQ=,tag:/1Rk/awOFfTGQvL9V9PnCA==,type:str]
            WEBUI_SECRET_KEY: ENC[AES256_GCM,data:v4fJeBB4M1I/RWqKT+44HwoNVlOsHTElytecpsOrT800PWcHvsaHD3TAqV4=,iv:BjP3xVBTP8YTjBa0SSStrNDDtPGc8IC3uGRNyFu0xgs=,tag:0ZVDm4q0zbRp4tzSQbHY8Q==,type:str]
        - name: ENC[AES256_GCM,data:Iziy36xBOxouVtfjFkOi0Wo6KA==,iv:uukWLZpAdFxmXdcJf6Nmm5FGtyceMPLttLG/p6YP2oo=,tag:GXYxzv7riwbgL3v7FFTS+g==,type:str]
          stringData:
            production.json: ENC[AES256_GCM,data:dGd33/Zllfoieh8df5redDM3Ij/Ab+R5zFccc16UQbxZ6WD2MBS9p4iZbG0vZ84Q1xO8tWsVZmlA5eb4GUoHc1ga0ne/H1ZxuIkJnvEu5l+qVvoLQBG/m3SXh/wQG1Obp2KWFZ01h6q0kGFZcY5uQp1F2ZJ0cKzmt3ioH4yO4EbCCqEqkjRNlkDnAZoTW8Q4xuB0+BtpG6jq1bsX0KWJ9NOvtAitqXzG+zvWnMpx81DqzLKLb/uHufEEMZZ9Kk/E7N/fr4lHWKx5PtaRJb7ff6s5IsRMSOZ3yCgu1IP1nuRm+g==,iv:sOnB+Yvpqgp8AsIo0fGUyxnKkTtWOLDjF5Pxp6c1PwM=,tag:eIhOc0ljo8TbvrfKVEX0Zg==,type:str]
        - name: ENC[AES256_GCM,data:uwlsdKDsaGrPTOXIdI7n/KHyLDGS,iv:WDkqSHO6XzxRsJW/ZBvc3OwcXridw2I/JSZpoVdD8h0=,tag:RFY2b9Z1aQqUbmwiw/8HvQ==,type:str]
          type: ENC[AES256_GCM,data:smzgGA/19CtQvLF5VGdNfsgrjJ2r9qYJjMI/ypLx,iv:qf6M0wMw5H/kyehanJBZigOzk1g++C6a27ezxLKS6Q0=,tag:px2t8RL81i3K58jYbdZDQw==,type:str]
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:NxnojJQoXT4ncfiGyx0IP6r6eU8qakgNWFmpsxq98YRraBqT8kpfGWs9MuqYxE2ZMkulDsaJgR3Or9/KBE6d5uG9i7yQDeiaPQPFgJyoymQVE7yH1AMIzqGBpC06/4GjM1yYY1uq+HoLZYjKAZKEFzekeZiqBsGDz/lqBAg=,iv:KftjTzGLptn46iBccW1yd/iBSJwkX/u9tqMzEAxUMzI=,tag:6rO/ADluroaQbnbgehHliQ==,type:str]
sops:
    age:
        - recipient: age1se1qd0xew8nru2cmy7u9mvy9wr8lxj2zs6k0fysthpdj8kjuuryn6vwv6fsh04
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZ5Ry9wUSBBMEZRVEZX
            aXlYQU45aW5admI5YkpiMWRIMGxzektGbXNWaGxoa3VxOGxRTwpvVmNGYTRobURB
            cm5EeGl0NEJzNHJQcHRFblp2VHp4aWdxSllhWk1nTkRzCi0tLSAxRkRtTDBQa1E5
            TnVRa3dkTHhHNWxaSUtMWEZ3SktUaDVWbWZTWDA0QjE4Cpg3CVP53vpwIUC3DKft
            C7OK6R3QxlBIDEoxAe+nTDiuaXFf4agOJLRO91wGYYDbLfYInX4J2nUSg3Y+3R3a
            oZQ=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye7q4uvexwhruvm5p9svw9z5tu58v9uk6r9pv4aue8j7v0lmpqus5ug9az
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUGtRMC9oaExVTHVzdEJO
            cFBjV1BuajlzNFRIengxNGtTQWFDNUJqWUNjCnlUWG9JT2FsTnRZMHVyYjlpQXY2
            dmtFemcza3NaK1VVZ3kvanhCVkdCTkEKLS0tICtEeDdQUUMxUzFTbTlzZkhRaEww
            ejhGd0V5ZzU0clVVc084Mm1QN1RPSmMKXMN8IpwaHXj2TC5gBoh5dKsn1JW4kfc/
            60S856zHsdx+l8lw7OudAywLm97z7M0dWP1SrFZunaDMnONw/mFsCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-05T11:25:17Z"
    mac: ENC[AES256_GCM,data:h1t6k6CfYTfp3wpg5+9cWEeyUf7mLL/0TgbEQlXQsaRen+c3RhOgptPBMeB3AGhVbwCDhYhWZ5NiARzMwa8iK0gFryDWa1qsK2BUGD3fwZQTlxhW1A+X8JxjVA1KbjhNwrXywH5gn3ld0Qg/Qoi7eiiIgx+tidcs3zRVZTtPfHQ=,iv:S8zIBHpoEIvkjOV8p/X4Tfn39qfFn+kwtYEWYu5Wy+Y=,tag:325tt9X2jVqjPaSkJWZyUA==,type:str]
    encrypted_suffix: Templates
    version: 3.10.2
---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sops-secrets
    namespace: cert-manager
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:+vztK5fiprvA4eD+hds=,iv:BXIqN/p/tlXDn0GnJagIZDtHjdGpEyJRd/pWTlQu3r4=,tag:FwvYa8tDVhTu0r+u/FBJMQ==,type:str]
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:PGSoeHHu+BqHnWhv3moI/F5gfko=,iv:N/gPw7erqLcKpRQCpDST60cWkMBXSsE5tP5pQnwNbDw=,tag:UyEUCh8LPo043CXtVc2XkQ==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:5qFhusPdd9VqdkdkNf2bAujcVIr+Zb2AM5HhVthTg9OajeBB3yiG9w==,iv:FWKR4Cw5Fc+GSh9VrXpymzsGyfPv6ZxozygveCUdgmU=,tag:FDNWOCllWWyEmjJ99rWuVg==,type:str]
sops:
    age:
        - recipient: age1se1qd0xew8nru2cmy7u9mvy9wr8lxj2zs6k0fysthpdj8kjuuryn6vwv6fsh04
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZ5Ry9wUSBBMEZRVEZX
            aXlYQU45aW5admI5YkpiMWRIMGxzektGbXNWaGxoa3VxOGxRTwpvVmNGYTRobURB
            cm5EeGl0NEJzNHJQcHRFblp2VHp4aWdxSllhWk1nTkRzCi0tLSAxRkRtTDBQa1E5
            TnVRa3dkTHhHNWxaSUtMWEZ3SktUaDVWbWZTWDA0QjE4Cpg3CVP53vpwIUC3DKft
            C7OK6R3QxlBIDEoxAe+nTDiuaXFf4agOJLRO91wGYYDbLfYInX4J2nUSg3Y+3R3a
            oZQ=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye7q4uvexwhruvm5p9svw9z5tu58v9uk6r9pv4aue8j7v0lmpqus5ug9az
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUGtRMC9oaExVTHVzdEJO
            cFBjV1BuajlzNFRIengxNGtTQWFDNUJqWUNjCnlUWG9JT2FsTnRZMHVyYjlpQXY2
            dmtFemcza3NaK1VVZ3kvanhCVkdCTkEKLS0tICtEeDdQUUMxUzFTbTlzZkhRaEww
            ejhGd0V5ZzU0clVVc084Mm1QN1RPSmMKXMN8IpwaHXj2TC5gBoh5dKsn1JW4kfc/
            60S856zHsdx+l8lw7OudAywLm97z7M0dWP1SrFZunaDMnONw/mFsCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-05T11:25:17Z"
    mac: ENC[AES256_GCM,data:h1t6k6CfYTfp3wpg5+9cWEeyUf7mLL/0TgbEQlXQsaRen+c3RhOgptPBMeB3AGhVbwCDhYhWZ5NiARzMwa8iK0gFryDWa1qsK2BUGD3fwZQTlxhW1A+X8JxjVA1KbjhNwrXywH5gn3ld0Qg/Qoi7eiiIgx+tidcs3zRVZTtPfHQ=,iv:S8zIBHpoEIvkjOV8p/X4Tfn39qfFn+kwtYEWYu5Wy+Y=,tag:325tt9X2jVqjPaSkJWZyUA==,type:str]
    encrypted_suffix: Templates
    version: 3.10.2
