apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sops-secrets
    namespace: admin
spec:
    # https://github.com/isindir/sops-secrets-operator/blob/147febf336f14bb2546eec020680ce1b2a2e96f1/api/v1alpha3/sopssecret_types.go#L33
    secretTemplates:
        - name: ENC[AES256_GCM,data:nKVW1E3R1kQ=,iv:xCDOlXCUnQk8+voaVnrsyGcU1UYex7Yd8CViH26uRPE=,tag:O17M183KGJz0PGorzTLfnw==,type:str]
          stringData:
            configuration.secret.yml: ENC[AES256_GCM,data:7I05w05OcO6QmbTkNdmtSW+uu/yPR0p+WjWjyDPbsEIAE6KjGPKIyY9CQNvE6v6sBi172LlLzXKDdiqFjr4uXioeL42w4J7eJVUdFvZv214cJrBRTrDPF8PYVJOwhGLBjAZs+ZvalDHkAEZuVd0SqhA3sNV6cOiLwgCd0oVaZJNFv417echS47ZZgeCNyLqWCAflgbHJ+xtsWDNRT9ntl/vmjzDx/3vv3hnUgk+xBmJgcN6YyRJo0euz2f5v3AE8MToGf7GJwZdfg73dLGcXYpcG2JjOAzPSNEOFkH+4Bu6tcvG4WJG4Vk2RL3rN+42yVgTeyiFawNZRDLjZjeEVMdNPYP3jDnO1DNtWoE6YZ7qW45ZHYinKVXQJV9rYklGtYFjYwPq97eiXmGao3zV7/3qL88lOAkxH4CJBDsn6t0/92drNMozMTcXbTD+5Y8ygFgA/i9bGRFuH3Tmwo/mCXzoIJTgRWve7arIk5kn40v8oCXv17m2app3mDA9cuwXWbivNOIYGbPjFm64UxJIRdLBS2W9gBaT9MOpsrgOzb6ktEuMaY+ge1+OPnvEyHw/wpImnIGjnKAbQKnZOfCkX33fqGm22CtSfMFCC9RKQydtoSc4kIuLQwOp9V8MWwvT3d3HcSscs8PNzpI4+1pyhS75mG0LQrMT41asnoyYs3umS7+BJ5tKIhHmWBW6Xy4j19A0GGH7TmG7m8lLUctepmiTMSORFFw6Jrj4PhOu1eIaEl1AZc+Q+ASblQygjT8llTYmm1V8nFNEuW8qqzyJf8b41LjtOWj9Lce4K6ztqb8q+bWy79wPdIS+I1aASN8m1FptQVgocz/fqL6KcwDv4xfM/63kVXceL2NIiM2pPiiYYXwlpEUusI5XGAOM/wynz4JE2pfq3G+f5Gu3Dm0/NdT+/j5OwzwLy9HGj9dSj9I3ZItzvyjMUuiRvcKZboFwb/H5+ZF7eJBUq7DC8teKHLa3jJcY5R2+6ODqO7p5gVgaUzmNmDg6rCynhg368feQ0Q8QfcxpkxClVMxzC0OMDKsaQJEU4S40hedq+oYdDi4/+wKMaDjmk2Zc0OPJb7AGmvaXlN7BS+czpQPl0ov6e2hbTNxcq8Ed0Q0vZNFjLc+ajWgNj5+mNwc4/Lnmto5T9bfY8ZdHXUYNyBdaVmSGW37Bf/rl6LIb/kUoRB2uCkqC6FAAIeZ7aBPJaKd0kOBS2tv00dFMtCNQi+oxCAMjFweAv31nn90GwBmKrgFl+44PSCqyTQlCFsbuVzJG8v/uHNNMm00FpwrCPkUj3fDlYmLy69PW7gvLM5CL2BZZaGJVGejlWNgeoCal5y4djech0cSmGPYoszXD/bpIcy0+b/jsMy44xRjRKexBwvRMnENAbnuZyaq7MIjjrxcp3IYARXJN4RMXq91xvW1W136eMbep1AjQyjCpFx6aB0Je+5GBOH/k00/8rKG8OpgMZFfml+1dOPUqZ8uavQ5EdjzhQ29M1tPtQ0rRXLw4xUDyb4QrW29i0oxyV5s5Rq0LwOw/VFp6SYmxlmPJaImoBPWJ5/2CzrOrMjzgDbH0BpJUW/QTS06iNxlDLqEM3sq3S5DvkpPThlbj7D/lZc+ejq4W8bxRafl04BIwh9jqfvBzVQIAh6rCQQCTfuSAOYrd+ZYWl4TRGh3C7ju/gPvaJTXw8J9cTJGUNB5LLu4zc/5tBMOezQOndmJFbmMtXlyi2A8dL8qF55MBPBl5QBMBTbA9a8DSf595E18gTV3xcl/PsIqWb0rf+FMun5fhk+z3aZLwLWTCjnVvzq3fnQuX84XfVPlmqI5++ye3+9lXOwvtxImN8LBI6Khr8eWvMeNJoG5OPPMbEDe7IApHw6uXWSoymTLR0mKf2opJmKpuoSV5ekNAIgbsB3i1l88exT3646eNlPkDv+W0r7tqioxuRKs/+LzA8M3eT47HAALPUvNNRatQ8QYbNKdBj9ymJpahoBT+EqLFU+YkxedI7hqP2GwiyVGOOVmffEuHz0m7yxgzFQjq4a8rmU3GFDMJCvV8dIUiqWvZKYRCmlku4Yd7FJRKT4msVSG6r12WaSAT5THB3yTUhFTWsa6dNNEphICsv7w+7mOz1j4Yr7IqEGNjfUwxVhOKtBE82BxqZbe+bqA1JVogT57RO6DFTbLhgcyEWKsCK8LpmBPbboaa0WighhqKsAfVW/YtqKDK5IVQ0E3NzODv4B9IWVnKOvZo4/Dj6PYtakx5lXlJn5QLEKHAF97nTKyy8OdiJHB1qa3zubmxM48fh/6yUYSQUhmFC+qkEcyKBfo4cINoybpsJ7+hXS4b5HWrv2sE3iWc+cCTWdBXsYyj3V3gjjAyxIfdUUqBrJZcd4bymyQvJB1ud44DATJaG2ultgKrt8Fk6lEbhiA0EwOqI8A4DHWiZ0LVs/1vybUmSXOIGHRhST4p1cbQcb2kXTmu0w2H1LXXC0/+bFjX/l9VMwLaOUP0fxPb3704pgbPmtZw1vCRgt0ABrkqP9tdsjfVzWG87m6TPu5JYaBKa6tEyrzxmhWZGYttNDbh1Grn8AW5TzUlw07NAJoer8lQ+0vPvGgV2xxYqpg236hxGFB5+t6gGJOuSvwvzLCj+cN7YbY6YYI+XI5dKemiSNAs8TDf4YKZNX98b3J1qKGIF+U55odjhrYiJkCkGJ6aojVIBCZLOf4vMFgI4+whH8bL5ABRaNn1kTf1KZUV929Y2j1P/cMxMGmzS37x1IhJd6dUT9AkPpQgp300rrqsJvfaIfUr/A062GAjsKO7sfhqq91ga9s5aK4BKQsa0s8NbusiyR6K7hkO7rxAaQqiaH0ytpD3vs2jRMPg5qmOt7cewpvfejyR4az8XWn95nvIHBZG16M9u0mWQWolD+00LeSO0/H+z4EfAQC33fgRLiSipZmhH/d0w4rrUbaM3GVv2DyeaSqZBQ8Du/FSRasZ6eF/9z3mLVxDSiHU/bOjEgv/VzlUS0SlDZ/KiqjhttpUqtWsBYb4UscJdYCvTSjMLx5wnBiVTPhmaxHjkBFh72jx5OPTDhcasD3Q4nmqrReDYHoM0seT8benAfQMRLPYIMonxQLdPdwm2uFGIg3OtWqhc5Q==,iv:axS0gINGOnwF5lAihns7yXm8KhMGdJnvLKx1u/eYzOE=,tag:ysE7YJ7XuDRirbL7CqSVNA==,type:str]
        - name: ENC[AES256_GCM,data:AwzNqAywh6UgtvLzmao=,iv:521LhNJ2PM1Gy4lKZygXhglo7FdcnqlTUffv4fDkOSM=,tag:1R2kiDJiHFDwNMAg9PdeBg==,type:str]
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:+R0Ra8kI2yI5FcnXMfPa00KxnfE=,iv:UjWw6q+goGD9SlP5njEe2sybLGzAG6BGz4Yug7B3BjA=,tag:uvie+IA4kLxVDEIniQMPoQ==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:XSsfP9DfPqJtKKwpUF1DwzGNqj3j/srFfEIDV280MP1TIwyR4uKgvw==,iv:GMulgmJHb+jyWlC36ijyG1kefzGuLuw0Kow1c+V4wIQ=,tag:F1R5NUurNzCFEyEZwuG3PQ==,type:str]
            RESTIC_REPOSITORY: ENC[AES256_GCM,data:ozGssvXpjcvpknkQ5TWg8PUJeQk62B7fsip/r1NH+EYIDQGAR2sBn7paAzlIPCY=,iv:85xSAINv3ig2ORVXdVleSvuTZ2Wv7TVLUS/tmzuuEto=,tag:XiV3q0kcE73obiKHZ7bJvw==,type:str]
            RESTIC_PASSWORD: ENC[AES256_GCM,data:Cpj1ZDTz8a8xYdjRVdfpYT9eR4BKlQBu207AN9DxrvoQDSui0EkkJFdvz6Y=,iv:NPlLyaFlxR2m8rhoxBfPqUTXJlXSfU6LsOEqu1tNzjo=,tag:U+/YNhAqT+JrKYI5KZ8JDg==,type:str]
sops:
    age:
        - recipient: age1se1qd0xew8nru2cmy7u9mvy9wr8lxj2zs6k0fysthpdj8kjuuryn6vwv6fsh04
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZ5Ry9wUSBBMEZRVEZX
            aXlYQU45aW5admI5YkpiMWRIMGxzektGbXNWaGxoa3VxOGxRTwpvVmNGYTRobURB
            cm5EeGl0NEJzNHJQcHRFblp2VHp4aWdxSllhWk1nTkRzCi0tLSAxRkRtTDBQa1E5
            TnVRa3dkTHhHNWxaSUtMWEZ3SktUaDVWbWZTWDA0QjE4Cpg3CVP53vpwIUC3DKft
            C7OK6R3QxlBIDEoxAe+nTDiuaXFf4agOJLRO91wGYYDbLfYInX4J2nUSg3Y+3R3a
            oZQ=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye7q4uvexwhruvm5p9svw9z5tu58v9uk6r9pv4aue8j7v0lmpqus5ug9az
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUGtRMC9oaExVTHVzdEJO
            cFBjV1BuajlzNFRIengxNGtTQWFDNUJqWUNjCnlUWG9JT2FsTnRZMHVyYjlpQXY2
            dmtFemcza3NaK1VVZ3kvanhCVkdCTkEKLS0tICtEeDdQUUMxUzFTbTlzZkhRaEww
            ejhGd0V5ZzU0clVVc084Mm1QN1RPSmMKXMN8IpwaHXj2TC5gBoh5dKsn1JW4kfc/
            60S856zHsdx+l8lw7OudAywLm97z7M0dWP1SrFZunaDMnONw/mFsCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-02T07:23:50Z"
    mac: ENC[AES256_GCM,data:kRGaKsAlMN9IjJje9ulheNyQBvN3UzLPnGzNoFEQzYYsptkq+6wxCL/P0qexjnEJ38yJMNwyaSHdliSdemIDaSqKIoD3/KJSNkCZ8meIQ8h9y4oFs29Ni9pLruqwZT4f0XIyOkTkKRdew81wVRXUKAz5MTOL607nwZ2ydEQyUZw=,iv:jMRpRwNdBLhq36JIt6pvHWzbEFdtB7TYc0G4yn9k0pQ=,tag:MPNm0AE5+JE0w+YXNZdifQ==,type:str]
    encrypted_suffix: Templates
    version: 3.10.2
---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sops-secrets
spec:
    # https://github.com/isindir/sops-secrets-operator/blob/147febf336f14bb2546eec020680ce1b2a2e96f1/api/v1alpha3/sopssecret_types.go#L33
    secretTemplates:
        - name: ENC[AES256_GCM,data:a+fPUmxfYg==,iv:G15dV3Fn3TBP7la3pX6tBbi7KnzEI+9riFuudUwjTeQ=,tag:2Gs+Lp4TiSZhIqtuXLBUCw==,type:str]
          stringData:
            secret_key: ENC[AES256_GCM,data:p8Al0QaszjFQOaMtrF/hegrSd8MZd+YnR6yS5H2DvwdPZZNTVu9fvJuWHKU=,iv:BCdi6YcLgTC58fdlhnU6aEbclHSf2Y6Yjn5oGwqvkf8=,tag:MRb8AXfZzJYV3s65Gh4Bqg==,type:str]
            mailer_passwd: ENC[AES256_GCM,data:N5MmTPRLiR2rcVng9QBs17O6wAMOxkdNdh0CL1jzECtRUmqltDud7MA/GtinD8D4iPM=,iv:SRzUeicnAhj63wnSjrivDSwbVqSM0yyE4LzbRqatskg=,tag:/rzjE2h3ZM3NeKiyJ46Dag==,type:str]
        - name: ENC[AES256_GCM,data:pXVLP0tAIAFyscVIS8lWMcv8,iv:H7eQ9ijQRjmDoRpRXM65A47XlA7GF3gz7u0xk+ZoXu8=,tag:nIaGzSuvts2VMCQxHY1I9A==,type:str]
          stringData:
            ANTHROPIC_API_KEY: ENC[AES256_GCM,data:FtHkdo4vYYWaAlPyypwqo+EbO0YMwQAK75LAWzW0gvx/ypNkXRMFlMmrLZnTrkVP6wuF2gd3DFBfp2pFJVuzho4QWZ1SR8PjtCh7/8SiSvHlaso5H9+8rRExtqeLY8ifu6V56/p1mM5XjlRm,iv:FPIonoWcWVPAjIwmUcrnYZrg0KALxQfwr5Y3CG+x8RA=,tag:zQslyXi3CTehU/cDDXNY1Q==,type:str]
            GOOGLE_PSE_API_KEY: ENC[AES256_GCM,data:0rFYiPTB3tx4hp/+GnfaGm2Hw4hdkFAj6aJOgeCWTLHHzRx9QAzP,iv:UwA3qq40v7msBkINKsLGkmi8Zlv8dFa9N37j+s94IEc=,tag:+oLtWCpI2Y63jG28MByw0w==,type:str]
            GOOGLE_PSE_ENGINE_ID: ENC[AES256_GCM,data:9KA/QiFsInKb1AOpPGGzvjw=,iv:tWbcz2tiQtb4Zd4bQjT2cvWwCGGxGWfmCLdYbuvBPbM=,tag:/dRuhQUduWLCWhT5kTXy+g==,type:str]
            OPENAI_API_KEY: ENC[AES256_GCM,data:9CgpEB+sRfziihaVAcO3yny5H2+48HT9Sjk8q0N3YULYyV4Mk/z8UCbQfziNry0AocCQ,iv:i++G4/sdNbqAPG4JwCehi3aAOp47pSTQ+6zm1FHVOKo=,tag:v9JDv5yIW1VAcKPF9gMMow==,type:str]
            SERPLY_API_KEY: ENC[AES256_GCM,data:lQH+xpOdBBHTs10fD04whAu/F6pz/25s,iv:zTOXcc9Q5vH+a+A7FL14sFCbJ1rlHxF0oneE5u+qRjQ=,tag:/1Rk/awOFfTGQvL9V9PnCA==,type:str]
            WEBUI_SECRET_KEY: ENC[AES256_GCM,data:v4fJeBB4M1I/RWqKT+44HwoNVlOsHTElytecpsOrT800PWcHvsaHD3TAqV4=,iv:BjP3xVBTP8YTjBa0SSStrNDDtPGc8IC3uGRNyFu0xgs=,tag:0ZVDm4q0zbRp4tzSQbHY8Q==,type:str]
        - name: ENC[AES256_GCM,data:Iziy36xBOxouVtfjFkOi0Wo6KA==,iv:uukWLZpAdFxmXdcJf6Nmm5FGtyceMPLttLG/p6YP2oo=,tag:GXYxzv7riwbgL3v7FFTS+g==,type:str]
          stringData:
            production.json: ENC[AES256_GCM,data:dGd33/Zllfoieh8df5redDM3Ij/Ab+R5zFccc16UQbxZ6WD2MBS9p4iZbG0vZ84Q1xO8tWsVZmlA5eb4GUoHc1ga0ne/H1ZxuIkJnvEu5l+qVvoLQBG/m3SXh/wQG1Obp2KWFZ01h6q0kGFZcY5uQp1F2ZJ0cKzmt3ioH4yO4EbCCqEqkjRNlkDnAZoTW8Q4xuB0+BtpG6jq1bsX0KWJ9NOvtAitqXzG+zvWnMpx81DqzLKLb/uHufEEMZZ9Kk/E7N/fr4lHWKx5PtaRJb7ff6s5IsRMSOZ3yCgu1IP1nuRm+g==,iv:sOnB+Yvpqgp8AsIo0fGUyxnKkTtWOLDjF5Pxp6c1PwM=,tag:eIhOc0ljo8TbvrfKVEX0Zg==,type:str]
        - name: ENC[AES256_GCM,data:uwlsdKDsaGrPTOXIdI7n/KHyLDGS,iv:WDkqSHO6XzxRsJW/ZBvc3OwcXridw2I/JSZpoVdD8h0=,tag:RFY2b9Z1aQqUbmwiw/8HvQ==,type:str]
          type: ENC[AES256_GCM,data:smzgGA/19CtQvLF5VGdNfsgrjJ2r9qYJjMI/ypLx,iv:qf6M0wMw5H/kyehanJBZigOzk1g++C6a27ezxLKS6Q0=,tag:px2t8RL81i3K58jYbdZDQw==,type:str]
          stringData:
            .dockerconfigjson: ENC[AES256_GCM,data:NxnojJQoXT4ncfiGyx0IP6r6eU8qakgNWFmpsxq98YRraBqT8kpfGWs9MuqYxE2ZMkulDsaJgR3Or9/KBE6d5uG9i7yQDeiaPQPFgJyoymQVE7yH1AMIzqGBpC06/4GjM1yYY1uq+HoLZYjKAZKEFzekeZiqBsGDz/lqBAg=,iv:KftjTzGLptn46iBccW1yd/iBSJwkX/u9tqMzEAxUMzI=,tag:6rO/ADluroaQbnbgehHliQ==,type:str]
sops:
    age:
        - recipient: age1se1qd0xew8nru2cmy7u9mvy9wr8lxj2zs6k0fysthpdj8kjuuryn6vwv6fsh04
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZ5Ry9wUSBBMEZRVEZX
            aXlYQU45aW5admI5YkpiMWRIMGxzektGbXNWaGxoa3VxOGxRTwpvVmNGYTRobURB
            cm5EeGl0NEJzNHJQcHRFblp2VHp4aWdxSllhWk1nTkRzCi0tLSAxRkRtTDBQa1E5
            TnVRa3dkTHhHNWxaSUtMWEZ3SktUaDVWbWZTWDA0QjE4Cpg3CVP53vpwIUC3DKft
            C7OK6R3QxlBIDEoxAe+nTDiuaXFf4agOJLRO91wGYYDbLfYInX4J2nUSg3Y+3R3a
            oZQ=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye7q4uvexwhruvm5p9svw9z5tu58v9uk6r9pv4aue8j7v0lmpqus5ug9az
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUGtRMC9oaExVTHVzdEJO
            cFBjV1BuajlzNFRIengxNGtTQWFDNUJqWUNjCnlUWG9JT2FsTnRZMHVyYjlpQXY2
            dmtFemcza3NaK1VVZ3kvanhCVkdCTkEKLS0tICtEeDdQUUMxUzFTbTlzZkhRaEww
            ejhGd0V5ZzU0clVVc084Mm1QN1RPSmMKXMN8IpwaHXj2TC5gBoh5dKsn1JW4kfc/
            60S856zHsdx+l8lw7OudAywLm97z7M0dWP1SrFZunaDMnONw/mFsCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-02T07:23:50Z"
    mac: ENC[AES256_GCM,data:kRGaKsAlMN9IjJje9ulheNyQBvN3UzLPnGzNoFEQzYYsptkq+6wxCL/P0qexjnEJ38yJMNwyaSHdliSdemIDaSqKIoD3/KJSNkCZ8meIQ8h9y4oFs29Ni9pLruqwZT4f0XIyOkTkKRdew81wVRXUKAz5MTOL607nwZ2ydEQyUZw=,iv:jMRpRwNdBLhq36JIt6pvHWzbEFdtB7TYc0G4yn9k0pQ=,tag:MPNm0AE5+JE0w+YXNZdifQ==,type:str]
    encrypted_suffix: Templates
    version: 3.10.2
---
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sops-secrets
    namespace: cert-manager
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:+vztK5fiprvA4eD+hds=,iv:BXIqN/p/tlXDn0GnJagIZDtHjdGpEyJRd/pWTlQu3r4=,tag:FwvYa8tDVhTu0r+u/FBJMQ==,type:str]
          stringData:
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:PGSoeHHu+BqHnWhv3moI/F5gfko=,iv:N/gPw7erqLcKpRQCpDST60cWkMBXSsE5tP5pQnwNbDw=,tag:UyEUCh8LPo043CXtVc2XkQ==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:5qFhusPdd9VqdkdkNf2bAujcVIr+Zb2AM5HhVthTg9OajeBB3yiG9w==,iv:FWKR4Cw5Fc+GSh9VrXpymzsGyfPv6ZxozygveCUdgmU=,tag:FDNWOCllWWyEmjJ99rWuVg==,type:str]
sops:
    age:
        - recipient: age1se1qd0xew8nru2cmy7u9mvy9wr8lxj2zs6k0fysthpdj8kjuuryn6vwv6fsh04
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHZ5Ry9wUSBBMEZRVEZX
            aXlYQU45aW5admI5YkpiMWRIMGxzektGbXNWaGxoa3VxOGxRTwpvVmNGYTRobURB
            cm5EeGl0NEJzNHJQcHRFblp2VHp4aWdxSllhWk1nTkRzCi0tLSAxRkRtTDBQa1E5
            TnVRa3dkTHhHNWxaSUtMWEZ3SktUaDVWbWZTWDA0QjE4Cpg3CVP53vpwIUC3DKft
            C7OK6R3QxlBIDEoxAe+nTDiuaXFf4agOJLRO91wGYYDbLfYInX4J2nUSg3Y+3R3a
            oZQ=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ye7q4uvexwhruvm5p9svw9z5tu58v9uk6r9pv4aue8j7v0lmpqus5ug9az
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUGtRMC9oaExVTHVzdEJO
            cFBjV1BuajlzNFRIengxNGtTQWFDNUJqWUNjCnlUWG9JT2FsTnRZMHVyYjlpQXY2
            dmtFemcza3NaK1VVZ3kvanhCVkdCTkEKLS0tICtEeDdQUUMxUzFTbTlzZkhRaEww
            ejhGd0V5ZzU0clVVc084Mm1QN1RPSmMKXMN8IpwaHXj2TC5gBoh5dKsn1JW4kfc/
            60S856zHsdx+l8lw7OudAywLm97z7M0dWP1SrFZunaDMnONw/mFsCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-02T07:23:50Z"
    mac: ENC[AES256_GCM,data:kRGaKsAlMN9IjJje9ulheNyQBvN3UzLPnGzNoFEQzYYsptkq+6wxCL/P0qexjnEJ38yJMNwyaSHdliSdemIDaSqKIoD3/KJSNkCZ8meIQ8h9y4oFs29Ni9pLruqwZT4f0XIyOkTkKRdew81wVRXUKAz5MTOL607nwZ2ydEQyUZw=,iv:jMRpRwNdBLhq36JIt6pvHWzbEFdtB7TYc0G4yn9k0pQ=,tag:MPNm0AE5+JE0w+YXNZdifQ==,type:str]
    encrypted_suffix: Templates
    version: 3.10.2
