apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sops-secrets
spec:
    secretTemplates:
        - name: seafile
          stringData:
            JWT_PRIVATE_KEY: your-secret-key-here
