apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sops-secrets
    namespace: cert-manager
spec:
    secretTemplates:
        - name: aws-access-key
          stringData:
            AWS_ACCESS_KEY_ID: ""
            AWS_SECRET_ACCESS_KEY: ""
