apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sops-secrets
spec:
    secretTemplates:
        - name: chess2online-config
          stringData:
            production.json: |
              {
                "knex": {
                  "client": "sqlite3",
                  "connection": {
                    "filename": "/app/db/production.sqlite3"
                  },
                  "useNullAsDefault": true
                },
                "auth": {
                  "secret": "REPLACE_WITH_SECRET"
                }
              }
        - name: chess2online-registry
          type: kubernetes.io/dockerconfigjson
          stringData:
            .dockerconfigjson: |
              {
                "auths": {
                  "registry.gitlab.com": {
                    "auth": "BASE64_ENCODED_USERNAME_PASSWORD"
                  }
                }
              }
