version: "3.5"

services:

  example:
    labels:
      # These labels are required in production to enable HTTPS support.
      # Remember to change "example" to the name of the exposed service.
      - traefik.http.routers.example.entrypoints=https
      - traefik.http.routers.example.tls=true
      - traefik.http.routers.example.tls.certresolver=le
