build-deploy-image:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  interruptible: true
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker buildx create --use --bootstrap
  script:
    - cd share
    - docker buildx build
      --provenance false
      -t $CI_REGISTRY_IMAGE/deploy:latest --push .
  # Run this job only on the main branch and only when the a related file
  # changes.
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - share/Dockerfile
        - share/ca.crt
