apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    namspace: admin
    name: sops-secrets
spec:
    secretTemplates:
        - name: backup-secrets
          stringData:
            AWS_ACCESS_KEY_ID: your-aws-access-key-id
            AWS_SECRET_ACCESS_KEY: your-aws-secret-access-key
            RESTIC_REPOSITORY: s3:s3.amazonaws.com/your-s3-bucket
            RESTIC_PASSWORD: your-restic-password
