version: "3.5"
services:

  heimdall:
    labels:
      - traefik.enable=true
      - traefik.http.routers.simple.entrypoints=https
      - traefik.http.routers.simple.tls=true
      - traefik.http.routers.simple.tls.certresolver=le
      - traefik.http.routers.simple.rule=Host(`${BASE_DOMAIN}`)
      - traefik.http.services.simple.loadbalancer.server.port=80
      - traefik.http.routers.simple.middlewares=auth@docker
