version: "3.5"
services:

  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${DATA_DIR}/heimdall/config:/config
    networks:
      - traefik
    restart: on-failure
    labels:
      - traefik.enable=true
      - traefik.http.routers.simple.entrypoints=https
      - traefik.http.routers.simple.tls=true
      - traefik.http.routers.simple.tls.certresolver=le
      - traefik.http.routers.simple.rule=Host(`${BASE_DOMAIN}`)
      - traefik.http.services.simple.loadbalancer.server.port=80
      - traefik.http.routers.simple.middlewares=auth@docker

networks:
  traefik:
    external: true
