apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sops-secrets
spec:
    secretTemplates:
        - name: zulip
          stringData:
            zulip__postgres_password: your-secret-key-here # openssl rand -base64 30
            zulip__rabbitmq_password: your-secret-key-here # openssl rand -base64 30
            zulip__redis_password: your-secret-key-here # openssl rand -base64 30
            zulip__memcached_password: your-secret-key-here # openssl rand -base64 30
            zulip__secret_key: your-secret-key-here # openssl rand -base64 30
            zulip__email_password: your-secret-key-here
            zulip__social_auth_oidc_secret: your-secret-key-here # must match the Authelia client_secret hash
