apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sops-secrets
    namespace: admin
spec:
    # https://github.com/isindir/sops-secrets-operator/blob/147febf336f14bb2546eec020680ce1b2a2e96f1/api/v1alpha3/sopssecret_types.go#L33
    secretTemplates:
        - name: ENC[AES256_GCM,data:U1FwBQSyVqk=,iv:dhcYLiJCTNSjkwmg7FEgxdZR60grIvmQdUcKUmtiKNU=,tag:Z5lDj39MPAum0YJGs1+Cjg==,type:str]
          stringData:
            AUTHELIA_SECRET: ENC[AES256_GCM,data:v/Ld0Jxfmr91yQ==,iv:JRsMflyMRc7CbG8jKjALhdHVLvirk4EL1h4F1l4agUA=,tag:hB1MRGqkI/n8Sb3rUUvNzw==,type:str]
sops:
    age:
        - recipient: age1pnmzawl6tcchdulgujr7k34rlz8tg27lepy2enydwjyxn9wxqe3spgrcze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZ2g1dXQxTjc3RDlOQnho
            S3BMd1p4UDQyam9XTEJhaytuRENuYTNiRXpNClZGeC9kYm1RbmpERlFpNkpjQUQ0
            bEZtbDhOYlRhT1dJTGhCRDVOa25PQ0UKLS0tIGdtMjFwd3ZvY1UxWGRQbnArbHZa
            SzRpbFk1ckRjd1gvNFR6TTRlVVZVMUkK78Y4XUEyvVgyfp9nQDsVgujBpKttBfR7
            xD/33udnVpPtpIYvHJxRLJ63lAn7rMtLtvzlQB/ZvKimuRbdo+glaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-28T03:18:12Z"
    mac: ENC[AES256_GCM,data:ExChF4SeJarqMPqdlVxhKj160t1MJJLjHUw94J+FLp1FM6bW4ddbXsMH5LSifbi3NXTKIT9vd+zdPez41dwctoE6RTHJpwaqJpU+dvIMEFxCzYyWKNTRnwh+KoAVXujPr+WpL4up9G2b9+/o5xU0LUy0SIawXlOX3vQnKsB65u8=,iv:bu7PC/TBn8Q3z3NRqPpg2fWWuJtr/t0B8hXdhEYJfOw=,tag:oCzgRuhcMpk+glz/7fkmCQ==,type:str]
    encrypted_suffix: Templates
    version: 3.10.2
