apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sops-secrets
    namespace: admin
spec:
    # https://github.com/isindir/sops-secrets-operator/blob/147febf336f14bb2546eec020680ce1b2a2e96f1/api/v1alpha3/sopssecret_types.go#L33
    secretTemplates:
        - name: ENC[AES256_GCM,data:U1FwBQSyVqk=,iv:dhcYLiJCTNSjkwmg7FEgxdZR60grIvmQdUcKUmtiKNU=,tag:Z5lDj39MPAum0YJGs1+Cjg==,type:str]
          stringData:
            AUTHELIA_SESSION_SECRET: ENC[AES256_GCM,data:eUcXvU8HNfdlggwcU2ETILQTu060hnFk6IaUjVOnHARg9OtqAmsEyg4/Xro=,iv:xs4GwJITR73b0JUXcT6M7cEGBM2DVZu7d7t1V5h5o10=,tag:arobbDvU79uyEvnvSUNjgg==,type:str]
            AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ENC[AES256_GCM,data:sJdGOv6wujANLI59BO3c6Vcavj4YCoEjQeeia9bGILnTD8gVXKVBk9vZ8GY=,iv:pxIe46TvLYRWVeOOBl4dtd16ZSPNrELWpr30gnID+/8=,tag:Jlhhyf0KD0JJpccyn4DfcA==,type:str]
            AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:FB0nZAtN5WJaMy1+ADeTysP+WuHJ8VxhnTYt6PIk/flBNWzWhE1nvP4PHuY=,iv:Gl1yNtcpD86ESmEBvkmi1RbsjP4e3XHBMgMLsP8YsnA=,tag:E3B3A+iIWp6+Rc+vza2ZEg==,type:str]
sops:
    age:
        - recipient: age1pnmzawl6tcchdulgujr7k34rlz8tg27lepy2enydwjyxn9wxqe3spgrcze
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZ2g1dXQxTjc3RDlOQnho
            S3BMd1p4UDQyam9XTEJhaytuRENuYTNiRXpNClZGeC9kYm1RbmpERlFpNkpjQUQ0
            bEZtbDhOYlRhT1dJTGhCRDVOa25PQ0UKLS0tIGdtMjFwd3ZvY1UxWGRQbnArbHZa
            SzRpbFk1ckRjd1gvNFR6TTRlVVZVMUkK78Y4XUEyvVgyfp9nQDsVgujBpKttBfR7
            xD/33udnVpPtpIYvHJxRLJ63lAn7rMtLtvzlQB/ZvKimuRbdo+glaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-28T04:20:17Z"
    mac: ENC[AES256_GCM,data:DLOm/eSgmO+TbMUQQ4Fhx7S53lCvbxQp0olaQMVCcIgWGYHgi5TMA22giQAQouXyelZtNuBCX8XLJCRTVrXwcxjwopHOaZoArxUQavsgIinlVdQFQU+F3990wpviKfc11LuaKKXPK/+kBORaBQbveYwE27dwu/AUVE00B6GB4cw=,iv:WrzZnLoaRJbEv3cUmhnhjx1Yw76vpF3lPBYLFjWd7a8=,tag:ZswD0n3jbMdkkgiXtJvHQA==,type:str]
    encrypted_suffix: Templates
    version: 3.10.2
