version: "3.5"

services:

  app:
    image: "jboss/keycloak"
    environment:
      - KEYCLOAK_HOSTNAME=keycloak.${BASE_DOMAIN}
    env_file: ./keycloak.env
    depends_on:
      - db
    networks:
      - internal
      - traefik
    restart: on-failure

  db:
    env_file: ./keycloak.env
    image: postgres:10.1
    volumes:
      - ${DATA_DIR}/keycloak/db:/var/lib/postgresql/data
    networks:
      - internal
    restart: on-failure

  forwardauth:
    image: funkypenguin/traefik-forward-auth
    env_file: ./forward-auth.${CLOUD_ENV}.env
    environment:
      - AUTH_HOST=forwardauth.${BASE_DOMAIN}
      - COOKIE_DOMAINS=${BASE_DOMAIN}
    networks:
      - traefik
    restart: on-failure
    depends_on:
      - app
    entrypoint: |-
      sh -c 'sh -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      # Wait for keycloak to start up
      while !  wget -O /dev/null -q http://app:8080/; do
        sleep 10
      done
      # Set up a host entry to hit traefik as the main keycloak server
      getent hosts traefik | awk '\''{ print \$$1 " keycloak.${BASE_DOMAIN}" }'\'' >> /etc/hosts
      # And this, see https://github.com/golang/go/issues/22846#issuecomment-346377144
      echo "hosts: files dns" > /etc/nsswitch.conf
      # Adjust the command line arguments to disable HTTPS or increase the log
      # level.
      ./traefik-forward-auth -cookie-secure=false
      EOF'

networks:
  traefik:
    external: true
  internal:
    internal: true
