version: "3.5"

services:

  # This is the simplest possible exposed service. It does not rely on any other
  # containers and does not require access control.
  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - ${DATA_DIR}/rabbitmq:/var/lib/rabbitmq
    networks:
      - traefik
      # If you need a private network to orchestrate several containers, specify
      # that in addition to the traefik network. All of the other containers in
      # the compose file should also use the same network.
      - internal
    restart: on-failure
    labels:
      - traefik.enable=true
      - traefik.subdomain=rabbitmq

      # If the service exposes more than a single port, you must specify which
      # one is the HTTP port using this.
      - traefik.http.services.rabbitmq.loadbalancer.server.port=15672

      # For services where you want to use the system-level access control, just
      # enable the middleware.
      #- traefik.http.routers.rabbitmq.middlewares=auth@docker

networks:
  # This network has to be pulled in from outside into every container that
  # wants to be hosted through traefik.
  traefik:
    external: true

  internal:
    # The network can be named anything, but setting internal on the network
    # will prevent it from being reachable from the outside (and containers
    # won't be able to reach the internet through it, either).
    internal: true
