---
  - hosts: '*'
    gather_facts: false
    become: yes
    tasks:
      - name: install self-destruct service
        copy:
          src: self-destruct.service
          dest: /etc/systemd/system/self-destruct.service
      - copy:
          src: hcloud-self-destruct
          dest: /usr/local/sbin/hcloud-self-destruct
          mode: 0755
      - systemd:
          daemon_reload: yes
          name: self-destruct
          enabled: true
          state: started

      - name: install ephemeral disk resizer
        copy:
          src: resize-ephemeral-disk.sh
          dest: /var/lib/cloud/scripts/per-boot/resize-ephemeral-disk.sh
          mode: 0755

      - name: install ansible systemd service
        copy:
          src: ansible.service
          dest: /etc/systemd/system/ansible.service
      - systemd:
          daemon_reload: yes
          name: ansible
          enabled: true

      - name: install auto-shutdown service
        copy:
          src: ps-auto-shutdown
          dest: /usr/local/bin/ps-auto-shutdown
          mode: 0755
        register: auto_shutdown_bin
      - copy:
          src: auto-shutdown.service
          dest: /etc/systemd/system/auto-shutdown.service
      - systemd:
          daemon_reload: yes
          name: auto-shutdown
          enabled: true
          state: started
        register: auto_shutdown_unit
      - systemd:
          name: auto-shutdown
          state: restarted
        when: not auto_shutdown_unit.changed and auto_shutdown_bin.changed

      - name: configure dotfiles
        when: no
        become: yes
        become_user: ubuntu
        block:
          - git:
              repo: https://github.com/CGamesPlay/dotfiles
              dest: /home/ubuntu/dotfiles
            register: result
          - shell:
              cmd: ./bootstrap.sh
              chdir: /home/ubuntu/dotfiles
            environment:
              HOME: /home/ubuntu
            when: result.changed
