version: "3.5"

services:
  app:
    image: chess2:latest
    volumes:
      - ./config.json:/app/config/production.json
      - ${DATA_DIR}/chess2:/app/db
    networks:
      - traefik
    restart: on-failure

networks:
  traefik:
    external: true
