---
  - name: verify services are operational
    hosts: '*'
    become: true
    gather_facts: false
    tasks:
      - name: services are running
        check_mode: yes
        systemd:
          name: "{{ item }}"
          state: started
        loop:
          - vault
          - vault-agent
          - consul
          - nomad
          - wg-quick@wg0
      - name: services are registered in consul
        command: "host {{ item }}.service.consul"
        check_mode: no
        register: result
        changed_when: no
        failed_when: '"has address" not in result.stdout'
        loop:
          - vault
          - consul
          - nomad
      - name: vault is unsealed
        command: vault status -format=json
        check_mode: no
        register: result
        changed_when: no
        failed_when: '(result.stdout | from_json).sealed'
