apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sops-secrets
spec:
    secretTemplates:
        - name: forgejo
          stringData:
            secret_key: your-secret-key-here
            mailer_passwd: smtp-password-here
