version: "3.5"

services:
  app:
    labels:
      - traefik.enable=true
      - traefik.subdomain=portainer
      - traefik.http.routers.portainer.entrypoints=https
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.tls.certresolver=le
      - traefik.http.routers.portainer.middlewares=auth@docker
