apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sops-secrets
spec:
    secretTemplates:
        - name: headscale
          stringData:
            OIDC_CLIENT_SECRET: QB/MGXjYPoqLlXP0Muu/rwDOj7TCA8TYmkpxFAPcyqE=
